-- Docker 初始化：确保业务账号 ERP_USER 可连接（与 .env 中 MYSQL_PASSWORD 一致）
USE mysql;

CREATE USER IF NOT EXISTS 'ERP_USER'@'%' IDENTIFIED BY '123456';
GRANT SELECT, INSERT, UPDATE, DELETE ON `erp`.* TO 'ERP_USER'@'%';
FLUSH PRIVILEGES;
